service: nano-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'ap-southeast-1'}

functions:
  - hello: 
      handler: index.handler
      memorySize: 128

plugins:
  - serverless-live-lambda-plugin
  - serverless-better-credentials